stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - .m2/repository

start test:
  stage: test
  image: maven:3.6.3-jdk-8
  tags:
    - 1housing-share-runner
  only:
    - merge_requests
    - web
    - pushes
  script:
    - mvn verify -P single
